# Netlify configuration for Next.js 16
# Using automatic OpenNext adapter (no plugin needed)

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--include=dev"

# Redirects - route all requests to Next.js server handler via Edge Function
[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/___netlify-edge-handler-node-middleware"
  status = 200
  force = false

# CORS Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400" 