# Netlify configuration for Next.js 16
# Updated for Next.js 16 support with explicit plugin
# See: https://www.netlify.com/changelog/next-js-16-deploy-on-netlify/

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--include=dev"

# Next.js 16 requires explicit plugin configuration
# The plugin manages ALL redirects, headers, and functions automatically
# DO NOT add manual redirects or publish directory
[[plugins]]
  package = "@netlify/plugin-nextjs" 