# Netlify configuration for Next.js 16
# Updated for Next.js 16 support with explicit plugin
# See: https://www.netlify.com/changelog/next-js-16-deploy-on-netlify/

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--include=dev"

# Next.js 16 requires explicit plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Serve static assets directly from Netlify's CDN and don't proxy them to the function
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Redirects - route all requests to Next.js server handler via Edge Function
[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/___netlify-edge-handler-node-middleware"
  status = 200
  force = false

# CORS Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400" 