# Netlify configuration for Next.js 16

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--include=dev"

# Essential Next.js plugin - handles routing, API routes, SSR, and ISR
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Scheduled Functions (cron jobs)
[[scheduledFunctions]]
  function = "app/api/scheduled-notifications/deliver/route.ts"
  schedule = "* * * * *"

# CORS Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400" 