# Netlify configuration for Next.js 16
# Usando adaptador automático Netlify Next Runtime v5
# Configuração minimalista seguindo template oficial: github.com/netlify-templates/next-platform-starter

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--include=dev"
